chore: check if required vars are available

diff --git a/.github/workflows/drawio-export.yml b/.github/workflows/drawio-export.yml
--- a/.github/workflows/drawio-export.yml
+++ b/.github/workflows/drawio-export.yml
@@ -28,10 +28,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Make Sure Required 'GH_APP_ID' and 'GH_APP_PRIVATE_KEY' Secrets are Available
-        if: ${{ !secrets.GH_APP_ID || !secrets.GH_APP_PRIVATE_KEY }}
+        shell: bash
         run: |
-          echo "Error: Required secrets 'GH_APP_ID' and 'GH_APP_PRIVATE_KEY' are not set."
-          exit 1
+          if [[ -z "${{ secrets.GH_APP_ID }}" || -z "${{ secrets.GH_APP_PRIVATE_KEY }}" ]]; then
+            echo "Error: Required secrets 'GH_APP_ID' and 'GH_APP_PRIVATE_KEY' are not set."
+            exit 1
+          fi
 
       - name: Get Github Access Token
         id: github_app_token
